# Generated by Django 2.2.6 on 2020-08-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200825_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='user_id',
        ),
    ]
