# Generated by Django 2.2.6 on 2020-08-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_delivery_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_delivery',
        ),
    ]
