# Generated by Django 2.2.6 on 2020-08-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_purchase_purchase_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.Delivery'),
            preserve_default=False,
        ),
    ]
